# Logstash 主配置文件

# 節點配置
node.name: "logstash-node-1"

# 數據路徑
path.data: /usr/share/logstash/data
path.logs: /usr/share/logstash/logs
path.settings: /usr/share/logstash/config

# HTTP API 配置
http.host: "0.0.0.0"
http.port: 9600

# X-Pack 監控配置
xpack.monitoring.enabled: false
xpack.monitoring.elasticsearch.hosts: ["http://elasticsearch:9200"]

# Pipeline 設定
pipeline.workers: 2
pipeline.output.workers: 1
pipeline.batch.size: 1000
pipeline.batch.delay: 50

# 日誌設定
log.level: info
slowlog.threshold.warn: 2s
slowlog.threshold.info: 1s
slowlog.threshold.debug: 500ms
slowlog.threshold.trace: 100ms

# 隊列配置
queue.type: persisted
queue.page_capacity: 64mb
queue.max_events: 0
queue.max_bytes: 1024mb
queue.checkpoint.writes: 1024

# Dead Letter Queue 設定
dead_letter_queue.enable: true
dead_letter_queue.max_bytes: 1024mb

# JVM 記憶體設定
config.reload.automatic: true
config.reload.interval: 3s

# 安全配置
api.ssl.enabled: false
api.auth.type: none