version: 2
updates:
  # Python dependencies for all services
  - package-ecosystem: "pip"
    directory: "/services/auth-service"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps(auth):"
      include: "scope"

  - package-ecosystem: "pip"
    directory: "/services/api-gateway"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps(gateway):"
      include: "scope"

  - package-ecosystem: "pip"
    directory: "/services/data-service"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps(data):"
      include: "scope"

  - package-ecosystem: "pip"
    directory: "/services/inference-service"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps(inference):"
      include: "scope"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/services/auth-service"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(docker):"

  - package-ecosystem: "docker"
    directory: "/services/api-gateway"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(docker):"

  - package-ecosystem: "docker"
    directory: "/services/data-service"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(docker):"

  - package-ecosystem: "docker"
    directory: "/services/inference-service"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(docker):"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(actions):"

  # Root Python dependencies (if any)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(root):"