version: 2
updates:
  # Python dependencies for auth-service
  - package-ecosystem: "pip"
    directory: "/src/services/auth-service"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "your-username"
    assignees:
      - "your-username"

  # Python dependencies for api-gateway
  - package-ecosystem: "pip"
    directory: "/src/services/api-gateway"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "your-username"
    assignees:
      - "your-username"

  # Python dependencies for data-service
  - package-ecosystem: "pip"
    directory: "/src/services/data-service"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "your-username"
    assignees:
      - "your-username"

  # Python dependencies for inference-service
  - package-ecosystem: "pip"
    directory: "/src/services/inference-service"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "your-username"
    assignees:
      - "your-username"

  # Docker dependencies for auth-service
  - package-ecosystem: "docker"
    directory: "/src/services/auth-service"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3

  # Docker dependencies for api-gateway
  - package-ecosystem: "docker"
    directory: "/src/services/api-gateway"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3

  # Docker dependencies for data-service
  - package-ecosystem: "docker"
    directory: "/src/services/data-service"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3

  # Docker dependencies for inference-service
  - package-ecosystem: "docker"
    directory: "/src/services/inference-service"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(actions):"

  # Root Python dependencies (if any)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(root):"