# GitLeaks 配置檔案
# 用於檢測程式碼中的敏感資訊洩露

[allowlist]
description = "允許的檔案和目錄"
paths = [
    '''\.md$''',
    '''\.txt$''',
    '''\.json$''',
    '''\.yaml$''',
    '''\.yml$''',
    '''\.toml$''',
    '''\.lock$''',
    '''\.log$''',
    '''\.gitignore$''',
    '''\.dockerignore$''',
    '''\.env\.example$''',
    '''\.env\.template$''',
    '''docs/''',
    '''test-results/''',
    '''coverage/''',
    '''node_modules/''',
    '''__pycache__/''',
    '''\.git/''',
    '''\.github/''',
    '''\.vscode/''',
    '''\.idea/'''
]

[detectors]
# 啟用所有檢測器
all = true

# 自定義檢測規則
[[rules]]
id = "custom-api-key"
description = "自定義 API 金鑰檢測"
regex = '''(?i)(api[_-]?key|api[_-]?token|access[_-]?token|secret[_-]?key)['"]?\s*[:=]\s*['"]?[a-zA-Z0-9]{32,}['"]?'''
tags = ["key", "api", "token"]

[[rules]]
id = "custom-database-url"
description = "資料庫連線字串檢測"
regex = '''(?i)(database_url|db_url|connection_string)['"]?\s*[:=]\s*['"]?[a-zA-Z]+://[^'"]+['"]?'''
tags = ["database", "connection"]

[[rules]]
id = "custom-password"
description = "密碼檢測"
regex = '''(?i)(password|passwd|pwd)['"]?\s*[:=]\s*['"]?[^'"]{8,}['"]?'''
tags = ["password", "credential"]

# 排除規則
[[rules]]
id = "exclude-test-files"
description = "排除測試檔案"
regex = '''(?i)(test|mock|fake|dummy|example)'''
tags = ["test", "mock"]