# GitLeaks configuration for Auto Video Generation System

title = "GitLeaks config for Auto Video Generation System"

[extend]
# Extend default config
useDefault = true

[[rules]]
description = "API Keys"
id = "api-key"
regex = '''(?i)(api_key|apikey|api-key)\s*[:=]\s*['""]?([a-z0-9\-_]{20,})['""]?'''
tags = ["key", "API"]

[[rules]]
description = "Database URLs"
id = "database-url"
regex = '''(?i)(database_url|db_url)\s*[:=]\s*['""]?(postgresql|mysql|mongodb)://[^\s'"]+['""]?'''
tags = ["database", "url"]

[[rules]]
description = "JWT Secrets"
id = "jwt-secret"
regex = '''(?i)(jwt_secret|jwt_key)\s*[:=]\s*['""]?([a-z0-9\-_]{16,})['""]?'''
tags = ["jwt", "secret"]

[[rules]]
description = "OAuth Secrets"
id = "oauth-secret"
regex = '''(?i)(client_secret|oauth_secret)\s*[:=]\s*['""]?([a-z0-9\-_]{20,})['""]?'''
tags = ["oauth", "secret"]

[[rules]]
description = "Redis URLs"
id = "redis-url" 
regex = '''(?i)(redis_url)\s*[:=]\s*['""]?redis://[^\s'"]+['""]?'''
tags = ["redis", "url"]

# Allowlist for test files and examples
[[allowlist]]
description = "Test files"
paths = [
    '''tests/.*''',
    '''.*_test\.py''',
    '''test_.*\.py''',
    '''.env.example''',
    '''docker-compose\.yml''',
]

[[allowlist]]
description = "Example configurations"
regexes = [
    '''your_.*_here''',
    '''example_.*''',
    '''test_.*''',
    '''fake_.*''',
    '''dummy_.*''',
]