apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: auto-video
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/component: gateway
    app.kubernetes.io/part-of: auto-video-system
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: api-gateway

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: auto-video
  labels:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/component: auth
    app.kubernetes.io/part-of: auto-video-system
spec:
  type: ClusterIP
  ports:
  - port: 8001
    targetPort: 8001
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: auth-service

---
apiVersion: v1
kind: Service
metadata:
  name: data-service
  namespace: auto-video
  labels:
    app.kubernetes.io/name: data-service
    app.kubernetes.io/component: data
    app.kubernetes.io/part-of: auto-video-system
spec:
  type: ClusterIP
  ports:
  - port: 8002
    targetPort: 8002
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: data-service

---
apiVersion: v1
kind: Service
metadata:
  name: inference-service
  namespace: auto-video
  labels:
    app.kubernetes.io/name: inference-service
    app.kubernetes.io/component: ai
    app.kubernetes.io/part-of: auto-video-system
spec:
  type: ClusterIP
  ports:
  - port: 8003
    targetPort: 8003
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: inference-service

---
apiVersion: v1
kind: Service
metadata:
  name: video-service
  namespace: auto-video
  labels:
    app.kubernetes.io/name: video-service
    app.kubernetes.io/component: video
    app.kubernetes.io/part-of: auto-video-system
spec:
  type: ClusterIP
  ports:
  - port: 8004
    targetPort: 8004
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: video-service

---
apiVersion: v1
kind: Service
metadata:
  name: ai-service
  namespace: auto-video
  labels:
    app.kubernetes.io/name: ai-service
    app.kubernetes.io/component: ai
    app.kubernetes.io/part-of: auto-video-system
spec:
  type: ClusterIP
  ports:
  - port: 8005
    targetPort: 8005
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: ai-service

---
apiVersion: v1
kind: Service
metadata:
  name: social-service
  namespace: auto-video
  labels:
    app.kubernetes.io/name: social-service
    app.kubernetes.io/component: social
    app.kubernetes.io/part-of: auto-video-system
spec:
  type: ClusterIP
  ports:
  - port: 8006
    targetPort: 8006
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: social-service

---
apiVersion: v1
kind: Service
metadata:
  name: trend-service
  namespace: auto-video
  labels:
    app.kubernetes.io/name: trend-service
    app.kubernetes.io/component: trends
    app.kubernetes.io/part-of: auto-video-system
spec:
  type: ClusterIP
  ports:
  - port: 8007
    targetPort: 8007
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: trend-service

---
apiVersion: v1
kind: Service
metadata:
  name: scheduler-service
  namespace: auto-video
  labels:
    app.kubernetes.io/name: scheduler-service
    app.kubernetes.io/component: scheduler
    app.kubernetes.io/part-of: auto-video-system
spec:
  type: ClusterIP
  ports:
  - port: 8008
    targetPort: 8008
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: scheduler-service

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: auto-video
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/component: ui
    app.kubernetes.io/part-of: auto-video-system
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: frontend

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: auto-video
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: auto-video-system
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    app.kubernetes.io/name: nginx

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: auto-video
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: auto-video-system
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app.kubernetes.io/name: postgres

---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: auto-video
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: cache
    app.kubernetes.io/part-of: auto-video-system
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  selector:
    app.kubernetes.io/name: redis