"""regenerate complete database schema

Revision ID: 01add939ac7e
Revises: 98359a2a002b
Create Date: 2025-08-08 17:09:06.737736

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "01add939ac7e"
down_revision: Union[str, None] = "98359a2a002b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """執行升級遷移"""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """執行降級遷移"""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
