"""Add crawler_tasks table

Revision ID: 20250803_002
Revises: 20250803_001
Create Date: 2025-08-03 12:00:00.000000

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "20250803_002"
down_revision = "20250803_001"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crawler_tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_name", sa.String(length=200), nullable=False),
        sa.Column("keywords", sa.Text(), nullable=False),
        sa.Column("target_url", sa.String(length=1000), nullable=True),
        sa.Column("schedule_type", sa.String(length=50), nullable=False),
        sa.Column("schedule_time", sa.String(length=100), nullable=True),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("task_name"),
    )
    op.create_index(op.f("ix_crawler_tasks_id"), "crawler_tasks", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_crawler_tasks_id"), table_name="crawler_tasks")
    op.drop_table("crawler_tasks")
    # ### end Alembic commands ###
