vulnerability:
  type:
    - os
    - library
  severity:
    - UNKNOWN
    - LOW
    - MEDIUM
    - HIGH
    - CRITICAL

secret:
  config: trivy-secret.yaml

license:
  full: true

cache:
  backend: redis
  redis:
    addr: redis:6379
    db: 0
    ttl: 24h

format: json
output: /reports/trivy-report.json

# 忽略特定漏洞 (如果已知且無法修復)
ignore:
  # CVE-2023-example: "已評估風險可接受"

# 自訂檢查規則
checks:
  - dockerfile-instruction-healthcheck
  - dockerfile-instruction-user
  - dockerfile-instruction-workdir
  - dockerfile-instruction-copy-add
  - secret-detection
  - license-detection

# 掃描配置
scan:
  # 離線模式
  offline: false
  
  # 跳過檔案
  skip-files:
    - "**/*.log"
    - "**/node_modules/**"
    - "**/.git/**"
    - "**/vendor/**"
    - "**/__pycache__/**"
  
  # 跳過目錄
  skip-dirs:
    - .git
    - node_modules
    - vendor
    - __pycache__
    - .pytest_cache
    - .coverage
  
  # 平台特定掃描
  platforms:
    - linux/amd64
    - linux/arm64

# 報告配置
report:
  format:
    - json
    - sarif
    - table
  
  severity-levels:
    - CRITICAL
    - HIGH
    - MEDIUM
    - LOW
  
  output-dir: /reports
  
  template: |
    Security Scan Report
    ====================
    
    Scan Date: {{ .CreatedAt }}
    Target: {{ .ArtifactName }}
    Type: {{ .ArtifactType }}
    
    Summary:
    - Critical: {{ .Results | length | where .Severity "CRITICAL" }}
    - High: {{ .Results | length | where .Severity "HIGH" }}
    - Medium: {{ .Results | length | where .Severity "MEDIUM" }}
    - Low: {{ .Results | length | where .Severity "LOW" }}
    
    Details:
    {{ range .Results }}
    {{ range .Vulnerabilities }}
    - {{ .VulnerabilityID }}: {{ .Title }} ({{ .Severity }})
      Package: {{ .PkgName }} {{ .InstalledVersion }}
      Fixed Version: {{ .FixedVersion }}
    {{ end }}
    {{ end }}

# 資料庫配置
db:
  # 漏洞資料庫更新
  update: true
  
  # 離線資料庫路徑
  # offline-db: /path/to/offline-db
  
  # Java 資料庫
  java-db: true
  
  # Python 資料庫  
  python-db: true
  
  # Node.js 資料庫
  nodejs-db: true