# Prometheus 配置 - Auto Video Generation System
# Phase 5: 監控告警系統

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'auto-video-generation'
    environment: '${ENVIRONMENT:-development}'

rule_files:
  - "alert_rules.yml"
  - "recording_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus 自身監控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter - 系統資源監控
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 5s
    metrics_path: /metrics

  # Redis 監控
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 10s

  # PostgreSQL 監控
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 10s

  # MinIO 監控
  - job_name: 'minio'
    static_configs:
      - targets: ['minio:9000']
    metrics_path: /minio/v2/metrics/cluster
    scrape_interval: 30s

  # API Gateway 監控
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8000']
    metrics_path: /metrics
    scrape_interval: 5s
    scrape_timeout: 10s

  # Auth Service 監控
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8001']
    metrics_path: /metrics
    scrape_interval: 10s

  # Video Service 監控
  - job_name: 'video-service'
    static_configs:
      - targets: ['video-service:8004']
    metrics_path: /metrics
    scrape_interval: 10s

  # AI Service 監控
  - job_name: 'ai-service'
    static_configs:
      - targets: ['ai-service:8002']
    metrics_path: /metrics
    scrape_interval: 15s

  # Frontend 監控 (如果有 metrics endpoint)
  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:3000']
    metrics_path: /api/metrics
    scrape_interval: 30s

  # Celery Worker 監控
  - job_name: 'celery-exporter'
    static_configs:
      - targets: ['celery-exporter:9540']
    scrape_interval: 15s

  # Nginx 監控 (如果使用)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 10s

  # Blackbox Exporter - 服務可用性監控
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://api-gateway:8000/health
        - http://auth-service:8001/health
        - http://video-service:8004/health
        - http://frontend:3000/
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # cAdvisor - 容器監控
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 10s
    metrics_path: /metrics

# 資料保留策略
storage:
  tsdb:
    retention.time: 30d
    retention.size: 10GB
    wal-compression: true

# 遠端寫入配置 (可選，用於長期儲存)
# remote_write:
#   - url: "https://prometheus-remote-write.example.com/api/v1/write"
#     basic_auth:
#       username: "${REMOTE_WRITE_USERNAME}"
#       password: "${REMOTE_WRITE_PASSWORD}"