# 備份系統配置

# 備份基本設定
backup:
  base_path: "/var/backups/auto-video"
  encryption: true
  compression: true
  checksum_verification: true
  parallel_jobs: 3
  
  # 保留政策
  retention_policy:
    daily: 7      # 保留 7 天的每日備份
    weekly: 4     # 保留 4 週的週備份
    monthly: 12   # 保留 12 個月的月備份
    yearly: 3     # 保留 3 年的年備份

# 儲存配置
storage:
  # 本機儲存
  local:
    enabled: true
    path: "/var/backups/auto-video/local"
    max_size_gb: 500
    
  # AWS S3 儲存
  s3:
    enabled: true
    bucket: "auto-video-backups"
    region: "us-west-2"
    access_key: "${AWS_ACCESS_KEY_ID}"
    secret_key: "${AWS_SECRET_ACCESS_KEY}"
    storage_class: "STANDARD_IA"  # STANDARD, STANDARD_IA, GLACIER
    encryption: "AES256"
    
  # Google Cloud Storage
  gcs:
    enabled: false
    bucket: "auto-video-backups-gcs"
    project_id: "${GCP_PROJECT_ID}"
    credentials_file: "/etc/gcp/service-account.json"
    
  # 遠端同步
  remote_sync:
    enabled: true
    host: "backup-server.company.com"
    user: "backup"
    path: "/backups/auto-video"
    ssh_key: "/etc/ssh/backup_rsa"

# 備份任務配置
jobs:
  # 資料庫備份
  - name: "postgresql-main"
    type: "database"
    source: "postgresql://autovideo:${DB_PASSWORD}@localhost:5432/autovideo"
    destination: "/var/backups/auto-video/database"
    schedule: "daily"  # daily, weekly, monthly, */hours
    encryption: true
    compression: true
    retention_days: 30
    priority: "high"
    dependencies: ["postgresql"]
    
  - name: "redis-cache"
    type: "database"
    source: "redis://localhost:6379/0"
    destination: "/var/backups/auto-video/redis"
    schedule: "daily"
    encryption: true
    compression: true
    retention_days: 7
    priority: "medium"
    dependencies: ["redis"]

  # 檔案系統備份
  - name: "user-uploads"
    type: "files"
    source: "/var/data/auto-video/uploads"
    destination: "/var/backups/auto-video/files"
    schedule: "daily"
    encryption: true
    compression: true
    retention_days: 90
    priority: "high"
    dependencies: []
    
  - name: "application-logs"
    type: "files"
    source: "/var/log/auto-video"
    destination: "/var/backups/auto-video/logs"
    schedule: "weekly"
    encryption: false
    compression: true
    retention_days: 30
    priority: "low"
    dependencies: []
    
  - name: "generated-videos"
    type: "files"
    source: "/var/data/auto-video/videos"
    destination: "/var/backups/auto-video/videos"
    schedule: "daily"
    encryption: true
    compression: false  # 影片已壓縮
    retention_days: 180
    priority: "high"
    dependencies: []

  # 配置備份
  - name: "system-configuration"
    type: "configuration"
    source: "."  # 當前目錄
    destination: "/var/backups/auto-video/config"
    schedule: "daily"
    encryption: true
    compression: true
    retention_days: 60
    priority: "high"
    dependencies: []

  # 容器備份
  - name: "api-gateway-container"
    type: "container"
    source: "auto-video-api-gateway"
    destination: "/var/backups/auto-video/containers"
    schedule: "weekly"
    encryption: true
    compression: true
    retention_days: 14
    priority: "medium"
    dependencies: ["docker"]
    
  - name: "database-container"
    type: "container"
    source: "auto-video-postgres"
    destination: "/var/backups/auto-video/containers"
    schedule: "weekly"
    encryption: true
    compression: true
    retention_days: 14
    priority: "high"
    dependencies: ["docker"]

# 監控與告警
monitoring:
  # 備份監控
  health_check:
    enabled: true
    check_interval: 3600  # 每小時檢查
    max_backup_age: 86400  # 24 小時內必須有成功備份
    
  # 指標收集
  metrics:
    prometheus:
      enabled: true
      port: 8091
      path: "/metrics"
    
  # 告警配置
  alerts:
    # 備份失敗告警
    backup_failure:
      enabled: true
      threshold: 1  # 連續失敗次數
      notification:
        - email
        - slack
        - webhook
    
    # 備份過期告警
    backup_outdated:
      enabled: true
      threshold: 25  # 超過 25 小時無備份
      notification:
        - email
        - slack
    
    # 儲存空間告警
    storage_space:
      enabled: true
      threshold: 85  # 儲存空間使用率 85%
      notification:
        - email
    
    # 備份大小異常告警
    backup_size_anomaly:
      enabled: true
      threshold: 50  # 備份大小變化超過 50%
      notification:
        - slack

# 通知配置
notifications:
  # 電子郵件
  email:
    enabled: true
    smtp_server: "${SMTP_SERVER}"
    smtp_port: 587
    username: "${SMTP_USERNAME}"
    password: "${SMTP_PASSWORD}"
    use_tls: true
    from: "backup@auto-video-system.com"
    to:
      - "ops@auto-video-system.com"
      - "admin@auto-video-system.com"
    
  # Slack
  slack:
    enabled: true
    webhook_url: "${SLACK_WEBHOOK_URL}"
    channel: "#backup-alerts"
    username: "Backup System"
    
  # Webhook
  webhook:
    enabled: true
    url: "http://alertmanager:9093/api/v1/alerts"
    headers:
      Content-Type: "application/json"
      Authorization: "Bearer ${WEBHOOK_TOKEN}"

# 災難恢復配置
disaster_recovery:
  # 恢復策略
  strategies:
    # 完整系統恢復
    full_recovery:
      steps:
        - type: "infrastructure_setup"
          description: "設定基礎設施"
        - type: "restore_database"
          description: "恢復資料庫"
        - type: "restore_files"
          description: "恢復檔案系統"
        - type: "restore_configuration"
          description: "恢復配置"
        - type: "start_services"
          description: "啟動服務"
        - type: "verify_system"
          description: "驗證系統"
    
    # 資料庫恢復
    database_recovery:
      steps:
        - type: "stop_services"
          description: "停止相關服務"
        - type: "restore_database"
          description: "恢復資料庫"
        - type: "start_services"
          description: "啟動服務"
        - type: "verify_database"
          description: "驗證資料庫"
    
    # 檔案恢復
    file_recovery:
      steps:
        - type: "restore_files"
          description: "恢復檔案"
        - type: "set_permissions"
          description: "設定權限"
        - type: "verify_files"
          description: "驗證檔案"

  # RTO/RPO 目標
  objectives:
    rto: 4  # Recovery Time Objective (小時)
    rpo: 1  # Recovery Point Objective (小時)
    
  # 測試排程
  testing:
    enabled: true
    frequency: "monthly"  # monthly, quarterly
    test_environments:
      - "staging"
      - "disaster-recovery"

# 安全配置
security:
  # 加密配置
  encryption:
    algorithm: "AES-256"
    key_rotation: true
    key_rotation_interval: 90  # 天
    
  # 存取控制
  access_control:
    backup_users:
      - username: "backup-operator"
        permissions: ["read", "write", "execute"]
      - username: "backup-admin"
        permissions: ["read", "write", "execute", "delete"]
    
    # 審計日誌
    audit_logging:
      enabled: true
      log_level: "INFO"
      log_file: "/var/log/backup-audit.log"

# 效能調整
performance:
  # 並發設定
  max_concurrent_jobs: 3
  max_concurrent_uploads: 2
  
  # 網路設定
  network:
    timeout: 300  # 秒
    retry_attempts: 3
    bandwidth_limit: "100MB"  # 頻寬限制
    
  # 資源限制
  resources:
    max_memory: "2GB"
    max_cpu_cores: 2
    io_priority: "best-effort"

# 除錯與日誌
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
  # 日誌檔案
  files:
    main: "/var/log/backup-system.log"
    error: "/var/log/backup-errors.log"
    audit: "/var/log/backup-audit.log"
  
  # 日誌輪轉
  rotation:
    max_size: "100MB"
    backup_count: 10
    
  # 遠端日誌
  remote_logging:
    enabled: true
    syslog_server: "log-server.company.com:514"
    facility: "local0"