# 健康檢查監控配置

# 監控設定
monitoring:
  interval: 30  # 檢查間隔 (秒)
  timeout: 10   # 請求超時 (秒)
  retries: 3    # 重試次數
  alert_threshold: 3  # 連續失敗次數觸發告警

# 服務配置
services:
  # 核心 API 服務
  - name: api-gateway
    type: http
    url: http://localhost:8080/health
    critical: true
    dependencies:
      - auth-service
      - data-service
    expected_response_time: 2.0
    health_check_path: /health
    
  - name: auth-service
    type: http
    url: http://localhost:8001/health
    critical: true
    dependencies:
      - postgresql
      - redis
    expected_response_time: 1.0
    
  - name: data-service
    type: http
    url: http://localhost:8002/health
    critical: true
    dependencies:
      - postgresql
      - s3
    expected_response_time: 1.5
    
  - name: ai-service
    type: http
    url: http://localhost:8003/health
    critical: true
    dependencies:
      - gpu-resources
    expected_response_time: 3.0
    
  - name: video-service
    type: http
    url: http://localhost:8004/health
    critical: true
    dependencies:
      - storage
      - ffmpeg
    expected_response_time: 2.0
    
  - name: social-service
    type: http
    url: http://localhost:8005/health
    critical: false
    dependencies:
      - external-apis
    expected_response_time: 5.0
    
  - name: trend-service
    type: http
    url: http://localhost:8006/health
    critical: false
    dependencies:
      - data-service
    expected_response_time: 2.0
    
  - name: inference-service
    type: http
    url: http://localhost:8007/health
    critical: true
    dependencies:
      - ai-models
    expected_response_time: 1.0
    
  - name: scheduler-service
    type: http
    url: http://localhost:8008/health
    critical: false
    dependencies:
      - celery
    expected_response_time: 1.0

  # 基礎設施服務
  - name: postgresql
    type: database
    connection: postgresql://autovideo:${DB_PASSWORD}@localhost:5432/autovideo
    critical: true
    max_connections: 100
    
  - name: redis
    type: redis
    connection: redis://localhost:6379/0
    critical: true
    
  - name: elasticsearch
    type: http
    url: http://localhost:9200/_cluster/health
    critical: false
    expected_response_time: 2.0
    
  - name: prometheus
    type: http
    url: http://localhost:9090/-/healthy
    critical: false
    expected_response_time: 1.0
    
  - name: grafana
    type: http
    url: http://localhost:3001/api/health
    critical: false
    expected_response_time: 2.0

  # Docker 容器服務
  - name: nginx
    type: docker
    container_name: auto-video-nginx
    critical: true
    
  - name: celery-worker
    type: docker
    container_name: auto-video-celery-worker
    critical: true
    
  - name: celery-beat
    type: docker
    container_name: auto-video-celery-beat
    critical: false

# 系統指標閾值
system_thresholds:
  cpu_usage: 80.0        # CPU 使用率警告閾值 (%)
  memory_usage: 85.0     # 記憶體使用率警告閾值 (%)
  disk_usage: 90.0       # 磁碟使用率警告閾值 (%)
  response_time: 5.0     # 響應時間警告閾值 (秒)
  error_rate: 5.0        # 錯誤率警告閾值 (%)

# 告警配置
alerts:
  # 電子郵件告警
  email:
    enabled: true
    smtp_server: ${SMTP_SERVER:-localhost:587}
    smtp_username: ${SMTP_USERNAME}
    smtp_password: ${SMTP_PASSWORD}
    use_tls: true
    from: health-monitor@auto-video-system.com
    to:
      - ops@auto-video-system.com
      - admin@auto-video-system.com
    
    # 告警等級配置
    levels:
      critical:
        to:
          - critical@auto-video-system.com
          - oncall@auto-video-system.com
        subject_prefix: "🚨 [CRITICAL]"
      
      high:
        to:
          - alerts@auto-video-system.com
        subject_prefix: "⚠️ [HIGH]"
      
      medium:
        to:
          - monitoring@auto-video-system.com
        subject_prefix: "📊 [MEDIUM]"

  # Webhook 告警
  webhook:
    enabled: true
    url: http://alertmanager:9093/api/v1/alerts
    timeout: 5
    headers:
      Content-Type: application/json
      Authorization: Bearer ${WEBHOOK_TOKEN}

  # Slack 告警
  slack:
    enabled: true
    webhook_url: ${SLACK_WEBHOOK_URL}
    channel: "#alerts"
    username: "Health Monitor"
    icon_emoji: ":warning:"

  # 告警規則
  rules:
    # 服務下線告警
    - name: service_down
      condition: status == "unhealthy"
      severity: critical
      message: "Service {{service_name}} is down"
      
    # 響應時間告警
    - name: slow_response
      condition: response_time > expected_response_time * 2
      severity: warning
      message: "Service {{service_name}} is responding slowly"
      
    # 依賴服務故障告警
    - name: dependency_failure
      condition: dependency_status == "unhealthy"
      severity: high
      message: "Service {{service_name}} dependency {{dependency}} is failing"
      
    # 系統資源告警
    - name: high_cpu_usage
      condition: cpu_usage > system_thresholds.cpu_usage
      severity: warning
      message: "High CPU usage: {{cpu_usage}}%"
      
    - name: high_memory_usage
      condition: memory_usage > system_thresholds.memory_usage
      severity: warning
      message: "High memory usage: {{memory_usage}}%"
      
    - name: high_disk_usage
      condition: disk_usage > system_thresholds.disk_usage
      severity: critical
      message: "High disk usage: {{disk_usage}}%"

# 恢復檢查配置
recovery:
  # 恢復驗證次數
  verification_count: 3
  
  # 恢復檢查間隔
  verification_interval: 10
  
  # 自動恢復動作
  auto_recovery:
    enabled: true
    max_attempts: 3
    
    actions:
      - type: restart_container
        condition: container_status == "exited"
        
      - type: clear_cache
        condition: service_name == "redis" and status == "unhealthy"
        
      - type: reload_config
        condition: response_time > expected_response_time * 3

# 報告配置
reporting:
  # 每日健康報告
  daily_report:
    enabled: true
    time: "09:00"
    recipients:
      - ops@auto-video-system.com
    
  # 每週健康報告
  weekly_report:
    enabled: true
    day: "monday"
    time: "09:00"
    recipients:
      - management@auto-video-system.com
    
  # 月度健康報告
  monthly_report:
    enabled: true
    day: 1
    time: "09:00"
    recipients:
      - executives@auto-video-system.com

# 儲存配置
storage:
  # 歷史資料保留
  retention:
    health_status: 30d    # 健康狀態資料保留 30 天
    metrics: 90d          # 指標資料保留 90 天
    alerts: 365d          # 告警記錄保留 1 年
  
  # 資料庫配置
  database:
    url: postgresql://health_monitor:${HEALTH_DB_PASSWORD}@localhost:5432/health_monitoring
    pool_size: 10
    max_overflow: 20

# 安全配置
security:
  # API 安全
  api_key: ${HEALTH_API_KEY}
  
  # TLS 配置
  tls:
    enabled: false
    cert_file: /etc/ssl/certs/health-monitor.crt
    key_file: /etc/ssl/private/health-monitor.key
  
  # 存取控制
  access_control:
    allowed_ips:
      - 127.0.0.1
      - 10.0.0.0/8
      - 172.16.0.0/12
      - 192.168.0.0/16

# 效能調整
performance:
  # 並發檢查數
  concurrent_checks: 10
  
  # 請求池大小
  connection_pool_size: 50
  
  # 快取設定
  cache:
    enabled: true
    ttl: 60  # 快取存活時間 (秒)
    
  # 批次處理
  batch_processing:
    enabled: true
    batch_size: 20
    max_wait_time: 5

# 除錯配置
debug:
  enabled: false
  log_level: INFO
  log_file: /var/log/health-monitor.log
  detailed_logging: false