http.host: "0.0.0.0"
xpack.monitoring.enabled: false
xpack.monitoring.elasticsearch.hosts: ["http://elasticsearch:9200"]

# Pipeline 設定
pipeline.workers: 2
pipeline.batch.size: 125
pipeline.batch.delay: 50

# 日誌設定
log.level: info
path.logs: /usr/share/logstash/logs

# Dead Letter Queue 設定
dead_letter_queue.enable: true
dead_letter_queue.max_bytes: 1024mb

# JVM 記憶體設定
config.reload.automatic: true
config.reload.interval: 3s